name: ci 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - run: pip install mkdocs-material 
      - run: python -V && echo ${PYTHONPATH}
    #  - run: $Env:PYTHONPATH="/home/runner/work/hollin-git.github.io/hollin-git.github.io"
      - run: pip install mkdocstrings[python]
      - run: export PYTHONPATH="/home/runner/work/hollin-git.github.io/hollin-git.github.io"
      - run: export PATH="/home/runner/work/hollin-git.github.io/hollin-git.github.io:$PATH"
      - run: ll -R /home/runner/work/hollin-git.github.io
      - run: mkdocs gh-deploy --force